version: "3"
services:
  lampandmaxaxiebot:
    build: .
    restart: always
    hostname: lampandmaxaxiebot
    container_name: lampandmaxaxiebot
    network_mode: host
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./axieBot.db:/axieBot.db
