version: "3"
services:
  prismbot:
    build: .
    restart: always
    hostname: lampandmaxaxiebot
    container_name: lampandmaxaxiebot
    network_mode: host
    logging:
      options:
        max-size: "10m"
        max-file: "3"
